"""Initial migration

Revision ID: dd8219ab4aa0
Revises: 
Create Date: 2025-03-03 15:00:00.506692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8219ab4aa0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('email', sa.String(100), nullable=False),
    )

    op.execute("""
           INSERT INTO users (username, email)
           VALUES
           ('user1', 'user1@example.com'),
           ('user2', 'user2@example.com'),
           ('user3', 'user3@example.com');
       """)


    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('users')
